---

- set_fact:
    gda_default_local_path: "{{ gda_base_local_path }}/{{ item.key }}"

- set_fact:
    archive_name: "{{ item.key }}.{{ item.value.archive_format | default(gda_archive_format) }}"

- name: clone and/or update and archive {{ item.key }} repo
  git:
    repo: "{{ item.value.url }}"
    dest: "{{ item.value.repo_local_path | default(gda_default_local_path) }}"
    force: "{{ item.value.force | default(gda_repo_force) }}"
    depth: "{{ item.value.depth | default(gda_repo_depth) }}"
    version: "{{ item.value.version | default(gda_repo_version) }}"
    clone: "{{ item.value.clone | default(gda_repo_clone) }}"
  delegate_to: 127.0.0.1

- name: prepare deployable archive of {{ item.key }} {{ item.value.subdir }}
  archive:
    path: "{{ item.repo_local_path | default(gda_default_local_path) }}/{{ item.value.subdir }}/*"
    dest: "{{ item.repo_local_path | default(gda_default_local_path) }}/{{ archive_name }}"
    exclude_path: ".git"
  when: item.value.subdir is defined
  delegate_to: 127.0.0.1

- name: prepare deployable archive of {{ item.key }}
  archive:
    path: "{{ item.value.repo_local_path | default(gda_default_local_path) }}"
    dest: "{{ item.value.repo_local_path | default(gda_default_local_path) }}/{{ archive_name }}"
    exclude_path: ".git"
  when: item.value.subdir is undefined
  delegate_to: 127.0.0.1
  